[tools]
act            = "0.2.83"
biome          = "2.3.10"
docker-cli     = "29.1.3"
docker-compose = "5.0.1"
node           = "22.21.1"
npm            = "11.6.2"
pnpm           = "10.26.2"
yarn           = "4.9.4"
