# Pushes the contents of the repo to the Codeberg mirror
name: ðŸªž Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'
jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with: { fetch-depth: 0 }
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url: git@codeberg.org:alicia/web-check.git
          ssh_private_key: ${{ secrets.CODEBERG_SSH }}
